### ISSUE TITLE
vs2017 打开提示找不到TestHelper

### ISSUE THREAD

**Issue by myxinzhanghao** [i542873057/SJNScaffolding#2]
ABPHelper和Dream.Scaffolding都有安装，不知道为什么还提示找不到TestHelper

**Comment by luoyunchong** [comment]
![image](https://user-images.githubusercontent.com/18613266/55370799-5554fb00-552e-11e9-99cb-3b2d4644a67e.png)

你可以把这个代码找回，或先注释掉引用 TestHelper的代码，那个是测试生成代码的，可以不用。 @myxinzhanghao

**Comment by luoyunchong** [comment]
testhelper已找回，拉取最新代码即可。不知道你说的ABPHelper和Dream.Scaffolding是什么，我们用的.NET  Core,前台运行起来是Razor Page。 @myxinzhanghao
